import { NextRequest, NextResponse } from "next/server";
import { getSessionUser } from "@/lib/auth/session";
import { adminDb } from "@/lib/db/firebase-admin";

export async function POST(request: NextRequest) {
  try {
    const user = await getSessionUser(request);

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json() as {
      cloudId: string;
      spaceKey: string;
      task: {
        title: string;
        dueDate: string;
        estimatedEffortHours: number;
        priority: string;
      };
      plan?: {
        risk: string;
        riskReason: string;
        requiredHours: number;
        availableHours: number;
        focusBlocks: Array<{ title: string; start: string; end: string; durationHours: number; description?: string }>;
      };
      advice?: any;
    };

    // Get Atlassian tokens
    const db = adminDb;
    

    const integrationDoc = await db
      .collection("users")
      .doc(user.id)
      .collection("integrations")
      .doc("atlassian")
      .get();

    if (!integrationDoc.exists) {
      return NextResponse.json(
        { error: "Atlassian not connected" },
        { status: 400 }
      );
    }

    const { accessToken } = integrationDoc.data() as { accessToken: string };

    // Build Confluence page content
    const content: any = {
      type: "doc",
      version: 1,
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: `🚀 Rescue Plan: ${body.task.title}` }],
        },
        {
          type: "panel",
          attrs: { panelType: "info" },
          content: [
            {
              type: "paragraph",
              content: [
                { type: "text", text: "Generated by " },
                { type: "text", text: "Deadline Rescue AI", marks: [{ type: "strong" }] },
                { type: "text", text: ` on ${new Date().toLocaleString()}` },
              ],
            },
          ],
        },
        {
          type: "heading",
          attrs: { level: 2 },
          content: [{ type: "text", text: "📋 Task Overview" }],
        },
        {
          type: "table",
          content: [
            {
              type: "tableRow",
              content: [
                {
                  type: "tableHeader",
                  content: [{ type: "paragraph", content: [{ type: "text", text: "Property" }] }],
                },
                {
                  type: "tableHeader",
                  content: [{ type: "paragraph", content: [{ type: "text", text: "Value" }] }],
                },
              ],
            },
            {
              type: "tableRow",
              content: [
                {
                  type: "tableCell",
                  content: [{ type: "paragraph", content: [{ type: "text", text: "Deadline" }] }],
                },
                {
                  type: "tableCell",
                  content: [{ type: "paragraph", content: [{ type: "text", text: new Date(body.task.dueDate).toLocaleString() }] }],
                },
              ],
            },
            {
              type: "tableRow",
              content: [
                {
                  type: "tableCell",
                  content: [{ type: "paragraph", content: [{ type: "text", text: "Estimated Effort" }] }],
                },
                {
                  type: "tableCell",
                  content: [{ type: "paragraph", content: [{ type: "text", text: `${body.task.estimatedEffortHours} hours` }] }],
                },
              ],
            },
            {
              type: "tableRow",
              content: [
                {
                  type: "tableCell",
                  content: [{ type: "paragraph", content: [{ type: "text", text: "Priority" }] }],
                },
                {
                  type: "tableCell",
                  content: [{ type: "paragraph", content: [{ type: "text", text: body.task.priority.toUpperCase() }] }],
                },
              ],
            },
          ],
        },
      ],
    };

    if (body.plan) {
      // Add risk analysis
      const riskPanel = body.plan.risk === "at-risk" ? "error" : body.plan.risk === "tight" ? "warning" : "success";
      content.content.push(
        {
          type: "heading",
          attrs: { level: 2 },
          content: [{ type: "text", text: "⚡ Risk Analysis" }],
        },
        {
          type: "panel",
          attrs: { panelType: riskPanel },
          content: [
            {
              type: "paragraph",
              content: [
                { type: "text", text: "Risk Level: ", marks: [{ type: "strong" }] },
                { type: "text", text: body.plan.risk.toUpperCase() },
              ],
            },
            {
              type: "paragraph",
              content: [{ type: "text", text: body.plan.riskReason }],
            },
            {
              type: "paragraph",
              content: [
                { type: "text", text: `Required: ${body.plan.requiredHours.toFixed(1)}h | Available: ${body.plan.availableHours.toFixed(1)}h` },
              ],
            },
          ],
        }
      );

      // Add focus blocks
      if (body.plan.focusBlocks.length > 0) {
        content.content.push(
          {
            type: "heading",
            attrs: { level: 2 },
            content: [{ type: "text", text: "📅 Recommended Focus Blocks" }],
          }
        );

        body.plan.focusBlocks.forEach((block, i) => {
          content.content.push({
            type: "paragraph",
            content: [
              { type: "text", text: `${i + 1}. `, marks: [{ type: "strong" }] },
              { type: "text", text: block.title, marks: [{ type: "strong" }] },
              { type: "text", text: ` (${block.durationHours.toFixed(1)}h)` },
            ],
          });

          content.content.push({
            type: "bulletList",
            content: [
              {
                type: "listItem",
                content: [
                  {
                    type: "paragraph",
                    content: [
                      { type: "text", text: `Start: ${new Date(block.start).toLocaleString()}` },
                    ],
                  },
                ],
              },
              {
                type: "listItem",
                content: [
                  {
                    type: "paragraph",
                    content: [
                      { type: "text", text: `End: ${new Date(block.end).toLocaleString()}` },
                    ],
                  },
                ],
              },
            ],
          });
        });
      }
    }

    if (body.advice) {
      // Add AI insights
      content.content.push(
        {
          type: "heading",
          attrs: { level: 2 },
          content: [{ type: "text", text: "🤖 AI-Powered Insights" }],
        },
        {
          type: "paragraph",
          content: [{ type: "text", text: body.advice.summary }],
        },
        {
          type: "heading",
          attrs: { level: 3 },
          content: [{ type: "text", text: "Next Best Action" }],
        },
        {
          type: "paragraph",
          content: [{ type: "text", text: body.advice.nextBestAction }],
        }
      );

      if (body.advice.taskBreakdown?.subtasks?.length > 0) {
        content.content.push(
          {
            type: "heading",
            attrs: { level: 3 },
            content: [{ type: "text", text: "Task Breakdown" }],
          },
          {
            type: "orderedList",
            content: body.advice.taskBreakdown.subtasks.map((subtask: any) => ({
              type: "listItem",
              content: [
                {
                  type: "paragraph",
                  content: [
                    { type: "text", text: subtask.title, marks: [{ type: "strong" }] },
                    { type: "text", text: ` (${subtask.estimatedHours}h)` },
                  ],
                },
              ],
            })),
          }
        );
      }
    }

    // Create Confluence page
    const confluenceResponse = await fetch(
      `https://api.atlassian.com/ex/confluence/${body.cloudId}/wiki/api/v2/pages`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
          Accept: "application/json",
        },

        body: JSON.stringify({
          spaceId: body.spaceKey,
          status: "current",
          title: `Rescue Plan: ${body.task.title}`,
          body: {
            representation: "atlas_doc_format",
            value: JSON.stringify(content),
          },
        }),
      }
    );

    if (!confluenceResponse.ok) {
      const error = await confluenceResponse.text();
      console.error("Confluence creation failed:", error);
      return NextResponse.json(
        { error: "Failed to create Confluence page", details: error },
        { status: 500 }
      );
    }

    const confluencePage = await confluenceResponse.json() as { id: string; title: string; _links: { webui: string } };

    // Get the base URL from resources
    const resources = integrationDoc.data()?.resources || [];
    const resource = resources.find((r: any) => r.id === body.cloudId);
    const baseUrl = resource?.url || `https://${body.cloudId}.atlassian.net`;

    return NextResponse.json({
      success: true,
      pageId: confluencePage.id,
      pageTitle: confluencePage.title,
      pageUrl: `${baseUrl}/wiki${confluencePage._links.webui}`,
    });
  } catch (error) {
    console.error("Confluence creation error:", error);
    return NextResponse.json(
      { error: "Failed to create Confluence page" },
      { status: 500 }
    );
  }
}
